### ISSUE TITLE
Multiline text not in body

### ISSUE THREAD

**Issue by modmoto** [romgere/text2stl#50] opened 2022-07-07 12:08 UTC
When having multiple lines it looks like this to me

![image](https://user-images.githubusercontent.com/9074759/177769523-68e9f8b6-1974-4b26-bc3a-b70b48114101.png)

**Comment by romgere** [comment] 2022-07-28 07:34
Duplicate of #49, I'm closing this in favor of #49. Thx @modmoto for opening this issue.

**Closed by romgere** 2022-07-28 07:34 UTC
